// OTP REGISTRATION
export const LOADING_OTP = 'LOADING_OTP';
export const SUCCESS_OTP = 'SUCCESS_OTP';
export const FAILED_OTP = 'FAILED_OTP';
export const NEW_USER = 'NEW_USER';

export const OTP_CONFIRM = 'OTP_CONFIRM';
export const OTP_FAIL = 'OTP_FAIL';

export const OTP_USER_LOADING = 'OTP_USER_LOADING';
export const OTP_USER_SUCCESS = 'OTP_USER_SUCCESS';
export const OTP_USER_FAIL = 'OTP_USER_FAIL';

export const USER_TYPE = 'USER_TYPE';
export const LOGOUT = 'LOGOUT';

export const AUTH_USER = 'AUTH_USER';
export const GET_USER = 'GET_USER';
export const FAILED_USER = 'FAILED_USER';
export const GET_SELLERS = 'GET_SELLERS';
export const FAILED_SELLERS = 'FAILED_SELLERS';
export const START_LOADING = 'START_LOADING';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const FAILED_CLOSE = 'FAILED_CLOSE';
export const NULL_SELLER = 'NULL_SELLER';
export const NOTIFICATION = 'NOTIFICATION';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const UPLOAD_PROFILE = 'UPLOAD_PROFILE';
export const FAILED_PROFILE = 'FAILED_PROFILE';
export const NULL_PROFILE = 'NULL_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FAILED_UPDATE = 'FAILED_UPDATE';
export const LOADING_NEAREST = 'LOADING_NEAREST';
export const GET_NEAREST = 'GET_NEAREST';
export const NULL_NEAREST = 'NUL_NEAREST';
export const FAILED_NEAREST = 'FAILED_NEAREST';
export const GET_NEARBY = 'GET_NEARBY';
export const REQUEST_CUSTOMER = 'REQUEST_CUSTOMER';
export const NULL_CUSTOMER = 'NULL_CUSTOMER';

export const LOADING_SERVICES = 'LOADING_SERVICES';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_FAILED = 'SERVICES_FAILED';

//--------------Order

export const LOADING_ORDER = 'LOADING_ORDER';
export const SUCCESS_ORDER = 'SUCCESS_ORDER';
export const FAIL_ORDER = 'FAIL_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
